services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  go-app:
    build:
      context: ./go-app
      dockerfile: Dockerfile
    container_name: go-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./go-app:/app
  # ui-app:
  #   image: ui-event-app
  #   build:
  #     context: ./UI-event-management
  #     dockerfile: ./Dockerfile
  #   environment:
  #     NODE_ENV: development
  #   ports:
  #     - 3000:3000

volumes:
  db_data:
