services:
  rn-app:
    build:
      context: ./rn-app
      dockerfile: Dockerfile
    container_name: event-queue-rn-app
    volumes:
      - ./rn-app:/app
      - rn_app_node_modules:/app/node_modules
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081"
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
  # db:
  #   image: postgres:15
  #   container_name: postgres-db
  #   restart: always
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - db_data:/var/lib/postgresql/data


  # mailhog:
  #   image: mailhog/mailhog
  #   container_name: mailhog
  #   restart: always
  #   ports:
  #     - "1025:1025" # SMTP port for sending emails
  #     - "8025:8025" # Web UI to view emails

volumes:
  rn_app_node_modules:
